### ISSUE TITLE
No module named 'telethon'

### ISSUE THREAD

**Issue by fly2hi** [deFiss/telegram_channel_duplicator#1]
PS D:\channelduop> python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from telegram_channel_duplicator.client import Client
  File "D:\channelduop\telegram_channel_duplicator\client.py", line 2, in <module>
    from telethon import TelegramClient, events
ModuleNotFoundError: No module named 'telethon'

**Comment by deFiss** [comment]
did you follow the instructions from the install section in readme?

**Comment by fly2hi** [comment]
Yes I did 
i am installing it on Windows 11
Python = 3.9
And from power shell i run this commands.

pip install -r requirements.txt
Rename config.json.example to config.json
python main.py

i did tried many other scripts, they are running fine but your shows me the error I mentioned before

**Comment by deFiss** [comment]
Perhaps you have problems with the virtual environment, try to recreate it, or create, if you have not already done so, and reinstall the dependencies.
