### ISSUE TITLE
Program everything works correctly, is an information

### ISSUE THREAD

**Issue by matts93** [deFiss/telegram_channel_duplicator#7]
I've been testing it for a few weeks and it works really well congratulations,
I have a request:
I have to modify the script according to my needs;
In addition to copying the messages, I would like it to make an API request to one of my servers with the copied message
where should i put my hands? in the code part?
A thousand thanks

**Comment by deFiss** [comment]
[Here](https://github.com/deFiss/telegram_channel_duplicator/blob/main/telegram_channel_duplicator/duplicator.py#L81) the method is called with sending a new message, you can change the code here or in the client.

[This](https://github.com/deFiss/telegram_channel_duplicator/blob/main/telegram_channel_duplicator/duplicator.py#L103) invokes an edit on the copied message if an edit on the source is detected.

**Comment by matts93** [comment]
Optimal!
implemented immediately
thank you so much you are number 1
